import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { DEFAULT_KEYWORD_GROUPS } from "../src/lib/config/keywords";
import { DEFAULT_TARGET_LOCATIONS } from "../src/lib/config/locations";

// Generates a single, paste-into-the-Supabase-SQL-Editor bootstrap script:
// migrations (in order) + the seed data — for environments where this
// session cannot reach the database directly (see README's networking note).

function sqlString(value: string | null | undefined): string {
  if (value === null || value === undefined) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlJson(value: unknown): string {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

function sqlBool(value: boolean): string {
  return value ? "true" : "false";
}

function main() {
  const migrationsDir = path.join(process.cwd(), "migrations");
  const migrationFiles = readdirSync(migrationsDir)
    .filter((f) => f.endsWith(".sql"))
    .sort();

  const parts: string[] = [
    "-- Ceramica Lead Generator — bootstrap script",
    "-- Generated by scripts/generate-bootstrap-sql.ts",
    "-- Paste this whole file into Supabase Dashboard -> SQL Editor -> New query -> Run.",
    "-- Safe to re-run: migrations use IF NOT EXISTS and seeds use ON CONFLICT DO NOTHING.",
    "",
  ];

  for (const file of migrationFiles) {
    parts.push(`-- ===== migrations/${file} =====`);
    parts.push(readFileSync(path.join(migrationsDir, file), "utf8").trim());
    parts.push("");
  }

  parts.push("-- ===== seed: keyword_groups =====");
  for (const group of DEFAULT_KEYWORD_GROUPS) {
    parts.push(
      `insert into keyword_groups (name, language, category, keywords, active) values (${sqlString(group.name)}, ${sqlString(group.language)}, ${sqlString(group.category)}, ${sqlJson(group.keywords)}, ${sqlBool(group.active)}) on conflict do nothing;`,
    );
  }
  parts.push("");

  parts.push("-- ===== seed: target_locations =====");
  for (const loc of DEFAULT_TARGET_LOCATIONS) {
    parts.push(
      `insert into target_locations (name, country, arabic_name, hebrew_name, target_market, active) values (${sqlString(loc.name)}, ${sqlString(loc.country)}, ${sqlString(loc.arabicName)}, ${sqlString(loc.hebrewName)}, ${sqlString(loc.targetMarket)}, ${sqlBool(loc.active)}) on conflict do nothing;`,
    );
  }
  parts.push("");

  parts.push("-- ===== seed: demo user =====");
  parts.push(
    `insert into users (email, name, role) values (${sqlString("saudraed31@gmail.com")}, ${sqlString("Saud")}, 'admin') on conflict (email) do nothing;`,
  );
  parts.push("");

  const output = parts.join("\n");
  const outPath = path.join(process.cwd(), "supabase-bootstrap.sql");
  writeFileSync(outPath, output, "utf8");
  console.log(`Wrote ${outPath} (${output.length} bytes)`);
}

main();
